### ISSUE TITLE
Memory Leak in WorldCluster

### ISSUE THREAD

**Issue by Meltie2013** [emu-dev/mangosvb#12]
**Current behaviour:**
When you logout or change characters, the WorldCluster (aka World Node) will start using major resources from the Processor. Character data is not being disposed as it should.

**Expected behaviour:**
When a character logs out and/or changing characters, the data being used should be disposed on logout.

**Steps to reproduce the problem:**
1) Start your servers like normal and login
2) Select a character and login to world or just logout
3) Look at the Performance of the WorldCluster

![image](https://user-images.githubusercontent.com/5354732/38790811-3ab3c536-4109-11e8-985e-23ae7dd74014.png)

No errors and/or outputs come with this issue. 

**Operating system:**
Windows 10

**Comment by Krilliac** [comment]
https://github.com/emu-dev/mangosvb/blob/master/Server/WorldCluster/Server/WC.Network.vb#L638

https://github.com/emu-dev/mangosvb/blob/master/Server/WorldCluster/Server/WC.Network.vb#L640

Socket.BeginRecieve = 80% CPU Leak

If HandingPackets = 13% CPU Leak

**Comment by Meltie2013** [comment]
I don't think its the network side, it points more to the authentication side of the network.
If you logout completely, and log back in, you will get a packet dropped error in the WC Console.

**Comment by Krilliac** [comment]
http://prntscr.com/j5vvsg

**Comment by Meltie2013** [comment]
Commit: https://github.com/emu-dev/mangosvb/commit/82c80e110fd4fe160dc67484bad5b34c18124919
