### ISSUE TITLE
Player Bank

### ISSUE THREAD

**Issue by Meltie2013** [emu-dev/mangosvb#3]
_From @Meltie2013 on November 5, 2013 8:51_

I noticed when you try to place in items in the Player Bank, the items either go gray or you lose them completely.  I believe SQL Query is not correct, or missing table data.

_Copied from original issue: mangosvb/serverZero#68_

**Comment by Meltie2013** [comment]
_From @billy1arm on November 5, 2013 12:3_

This may also be related to #19 

Did you see any message on the console ?

**Comment by Meltie2013** [comment]
Nope, just turned the items gray or just made them disappear basicly.

**Comment by Meltie2013** [comment]
_From @wowadict on November 7, 2013 7:10_

Come to think of it, I kind of remember a long time ago finding that one of the methods being called in the vendor stuff had the bag and slot reversed in the parameters, and it caused some thing like this.

**Comment by Meltie2013** [comment]
_From @wowadict on November 7, 2013 7:16_

WS.Npc.vb in the On_CMSG_BUY_ITEM_IN_SLOT method there is a call to ItemSETSLOT method that has them reversed, does not seem like that would effect the bank stuff, but it may have some thing to do with issue #19

**Comment by Meltie2013** [comment]
_From @wowadict on November 7, 2013 7:26_

Hmmm. On_CMSG_AUTOBANK_ITEM and On_CMSG_AUTOSTORE_BANK_ITEM don't do anything they both have a TODO: Do real moving comment in them, also I have no idea what is accomplished with this line If srcBag = 0 Then srcBag = 0 in those two methods.

**Comment by Meltie2013** [comment]
_From @Kaev on September 5, 2015 19:29_

Also this one https://github.com/mangosvb/serverZero/commit/8af5f8d973c3859181f46141b96d6939d8786a08

**Comment by Meltie2013** [comment]
This issue was fixed in a prev commit posted above.

**Comment by billy1arm** [comment]
@Meltie2013 - would you mind letting me know if there are any commits which need to be ported back to the main repo... Thanks
