### ISSUE TITLE
Items have a chance to not be added to you're inventory.

### ISSUE THREAD

**Issue by Meltie2013** [emu-dev/mangosvb#8]
_From @jaxx56 on September 2, 2015 8:41_

[CHARACTER] Error Reading From MySQL Database Duplicate entry '92' fo
r key 'PRIMARY'
[CHARACTER] Update string was: INSERT INTO characters_inventory (item
_guid, item_owner, item_creator, item_giftCreator, item_stackCount, item_durabil
ity, item_chargesLeft, item_random_properties, item_id, item_flags, item_enchant
ment, item_textId)  VALUES (92, "55", 0, 0, 1, 70, 0, 0, 22491, 0, '', 0);

_Copied from original issue: mangosvb/serverZero#96_

**Comment by billy1arm** [comment]
@Meltie2013 - needs to either perform a check first and perform an update rather than an insert 
OR
it needs to perform a delete on the existing item first, then perform the insert.

**Comment by Meltie2013** [comment]
This is our current function to add new items, update and remove them. Must be more to this then the query failing. I'll have to go through the strings and see if the table rows are matching or not. All checks are there.

    Private Sub SaveAsNew()
        'DONE: Save to SQL
        Dim tmpCmd As String = "INSERT INTO characters_inventory (item_guid"
        Dim tmpValues As String = " VALUES (" & GUID - GUID_ITEM
        tmpCmd = tmpCmd & ", item_owner"
        tmpValues = tmpValues & ", """ & OwnerGUID & """"
        tmpCmd = tmpCmd & ", item_creator"
        tmpValues = tmpValues & ", " & CreatorGUID
        tmpCmd = tmpCmd & ", item_giftCreator"
        tmpValues = tmpValues & ", " & GiftCreatorGUID
        tmpCmd = tmpCmd & ", item_stackCount"
        tmpValues = tmpValues & ", " & StackCount
        tmpCmd = tmpCmd & ", item_durability"
        tmpValues = tmpValues & ", " & Durability
        tmpCmd = tmpCmd & ", item_chargesLeft"
        tmpValues = tmpValues & ", " & ChargesLeft
        tmpCmd = tmpCmd & ", item_random_properties"
        tmpValues = tmpValues & ", " & RandomProperties
        tmpCmd = tmpCmd & ", item_id"
        tmpValues = tmpValues & ", " & ItemEntry
        tmpCmd = tmpCmd & ", item_flags"
        tmpValues = tmpValues & ", " & _flags

        'DONE: Saving enchanments
        Dim temp As New ArrayList
        For Each enchantment As KeyValuePair(Of Byte, TEnchantmentInfo) In Enchantments
            temp.Add(String.Format("{0}:{1}:{2}:{3}", enchantment.Key, enchantment.Value.ID,
                                   enchantment.Value.Duration, enchantment.Value.Charges))
        Next
        tmpCmd = tmpCmd & ", item_enchantment"
        tmpValues = tmpValues & ", '" & Join(temp.ToArray, " ") & "'"
        tmpCmd = tmpCmd & ", item_textId"
        tmpValues = tmpValues & ", " & ItemText

        tmpCmd = tmpCmd & ") " & tmpValues & ");"
        CharacterDatabase.Update(tmpCmd)
    End Sub

    Public Sub Save(Optional ByVal saveAll As Boolean = True)
        Dim tmp As String = "UPDATE characters_inventory SET"

        tmp = tmp & " item_owner=""" & OwnerGUID & """"
        tmp = tmp & ", item_creator=" & CreatorGUID
        tmp = tmp & ", item_giftCreator=" & GiftCreatorGUID
        tmp = tmp & ", item_stackCount=" & StackCount
        tmp = tmp & ", item_durability=" & Durability
        tmp = tmp & ", item_chargesLeft=" & ChargesLeft
        tmp = tmp & ", item_random_properties=" & RandomProperties
        tmp = tmp & ", item_flags=" & _flags

        'DONE: Saving enchanments
        Dim temp As New ArrayList
        For Each enchantment As KeyValuePair(Of Byte, TEnchantmentInfo) In Enchantments
            temp.Add(String.Format("{0}:{1}:{2}:{3}", enchantment.Key, enchantment.Value.ID,
                                   enchantment.Value.Duration, enchantment.Value.Charges))
        Next
        tmp = tmp & ", item_enchantment=""" & Join(temp.ToArray, " ") & """"
        tmp = tmp & ", item_textId=" & ItemText

        tmp = tmp & " WHERE item_guid = """ & (GUID - GUID_ITEM) & """;"

        CharacterDatabase.Update(tmp)

        If ITEMDatabase(ItemEntry).IsContainer() AndAlso saveAll Then
            For Each item As KeyValuePair(Of Byte, ItemObject) In Items
                item.Value.Save()
            Next
        End If
    End Sub

    Public Sub Delete()
        'DONE: Check if item is petition
        If _
            ItemEntry = PETITION_GUILD Then _
            CharacterDatabase.Update("DELETE FROM petitions WHERE petition_itemGuid = " & GUID - GUID_ITEM & ";")
        CharacterDatabase.Update(String.Format("DELETE FROM characters_inventory WHERE item_guid = {0}", GUID - GUID_ITEM))

        If ITEMDatabase(ItemEntry).IsContainer() Then
            For Each item As KeyValuePair(Of Byte, ItemObject) In Items
                item.Value.Delete()
            Next
        End If
        Dispose()
    End Sub
